package fr.uvsq.javaproject;

    import java.io.File;
	import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

	/**
	 *
	 * @author weswes1991
	 */
	public class Interface_rdf extends javax.swing.JFrame {

	    /**
	     * Creates new form interface_rdf
	     */
	    public Interface_rdf() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        chemin = new javax.swing.JTextField();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        res = new javax.swing.JTable();
	        jSeparator1 = new javax.swing.JSeparator();
	        jLabel2 = new javax.swing.JLabel();
	        cmd_search = new javax.swing.JButton();
	        jMenuBar1 = new javax.swing.JMenuBar();
	        jMenu2 = new javax.swing.JMenu();
	        cmd_brow = new javax.swing.JMenuItem();
	        cmd_exit = new javax.swing.JMenuItem();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jPanel1.setLayout(null);

	        chemin.setBackground(new java.awt.Color(204, 204, 204));
	        chemin.setToolTipText("Chemin sur dique");
	        chemin.setEnabled(false);
	        jPanel1.add(chemin);
	        chemin.setBounds(170, 30, 630, 40);
	        res.setBackground(new java.awt.Color(204, 204, 204));
	        res.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {

	            },
	            new String [] {

	            }
	        ));
	        jScrollPane1.setViewportView(res);

	        jPanel1.add(jScrollPane1);
	        jScrollPane1.setBounds(30, 110, 920, 402);
	        jPanel1.add(jSeparator1);
	        jSeparator1.setBounds(170, 80, 630, 20);

	        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wallpaper658185.jpg"))); // NOI18N
	        jPanel1.add(jLabel2);
	        jLabel2.setBounds(0, 0, 980, 640);

	        cmd_search.setText("Parcourir");
	        cmd_search.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cmd_searchActionPerformed(evt);
	            }
	        });
	        jPanel1.add(cmd_search);
	        cmd_search.setBounds(580, 80, 100, 40);

	        jMenu2.setText("File");

	        cmd_brow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
	        cmd_brow.setText("Browse");
	        cmd_brow.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cmd_browActionPerformed(evt);
	            }
	        });
	        jMenu2.add(cmd_brow);

	        cmd_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
	        cmd_exit.setText("Exit");
	        cmd_exit.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cmd_exitActionPerformed(evt);
	            }
	        });
	        jMenu2.add(cmd_exit);

	        jMenuBar1.add(jMenu2);

	        setJMenuBar(jMenuBar1);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
	        );

	        setSize(new java.awt.Dimension(995, 697));
	        setLocationRelativeTo(null);
	    }// </editor-fold>                        

	    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        JFileChooser chooser=new JFileChooser();
	        chooser.showOpenDialog(null);
	        File f=chooser.getSelectedFile();
	        String filename=f.getAbsolutePath();
	        chemin.setText(filename);
	    }                                          
		private void readRdf(String chemain){
			RDF rdf = new RDF(chemain);
			MyTable mt = new MyTable(rdf);
			this.res.setModel(mt);
	
		}
	    private void cmd_browActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        JFileChooser chooser=new JFileChooser();
	        FileNameExtensionFilter filter = new FileNameExtensionFilter("RDF", "rdf");
			    chooser.setFileFilter(filter);
			    int returnVal = chooser.showOpenDialog(null);
			    if(returnVal == JFileChooser.APPROVE_OPTION) {
			       System.out.println("You chose to open this file: " + chooser.getSelectedFile().getPath());
			       readRdf(chooser.getSelectedFile().getPath());
			    }
	        File f=chooser.getSelectedFile();
	        String filename=f.getAbsolutePath();
	        chemin.setText(filename);

	        
	    }                                        

	    private void cmd_exitActionPerformed(java.awt.event.ActionEvent evt) {                                         
	           int p= JOptionPane.showConfirmDialog(null, "Do you really want to quit","Quit",JOptionPane.YES_NO_OPTION);
	           if(p==0){
	           System.exit(0);
               }
	    }                                        

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Interface_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Interface_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Interface_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Interface_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Interface_rdf().setVisible(true);
	            }
	        });
	    }
	    // Variables declaration - do not modify                     
	    private javax.swing.JTextField chemin;
	    private javax.swing.JMenuItem cmd_brow;
	    private javax.swing.JMenuItem cmd_exit;
	    private javax.swing.JButton cmd_search;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JMenu jMenu2;
	    private javax.swing.JMenuBar jMenuBar1;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JSeparator jSeparator1;
	    private javax.swing.JTable res;
	    // End of variables declaration                   
	}
